version: '3'

services:
  # maria-db:
  #   image: mariadb:11
  #   restart: always
  #   command: --default-authentication-plugin=mysql_native_password
  #   networks:
  #     - ums-back-office
  #   volumes:
  #     - db-data:/var/lib/mysql

  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: ./Dockerfile
  #   networks:
  #     - ums-user-facing


  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    networks:
      - ums-user-facing
      - ums-back-office
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    # restart: always
  
  redis:
    image: redis
    restart: always
    command: redis-server --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - "6379:6379"
    networks:
      - ums-back-office

  worker:
    image: worker
    build: ./redis-queue/worker
    networks:
      - ums-back-office
  
  # nginx: #proxy
  #   image: nginx:alpine
  #   container_name: nginx-app
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "7887:80"
  #   depends_on:
  #     # - frontend
  #     - backend

  # proxy:
  #   image: nginx:alpine
  #   ports:
  #     - "7887:80"
  #   networks:
  #     - ums-user-facing
  #   depends_on:
  #     - frontend
  #     - backend
  #   volumes:
  #     - ./frontend/proxy/default.conf /etc/nginx/conf.d/default.conf

volumes:
  db-data:
    driver: local
networks:
  ums-user-facing:
  ums-back-office:
