version: '3'

services:
  redis:
    image: redis
    restart: always
    command: redis-server --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - "6379:6379"
    networks:
      - worker-net
  preview_worker:
    image: preview_worker
    build:
      context: ./worker
      dockerfile: ./Preview/Dockerfile
    networks:
      - worker-net
  convertor_worker:
    image: convertor_worker
    build:
      context: ./worker
      dockerfile: ./Convertor/Dockerfile
    networks:
      - worker-net
  chunk_worker:
    image: chunk_worker
    build:
      context: ./worker
      dockerfile: ./Chunk/Dockerfile
    networks:
      - worker-net


networks:
  worker-net: