redis:
  host: redis
  port: 6379
  db_number: 0
  queue_name: video_queue
  password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

s3:
  secret_key: TCYSmBQuMOkT2mAPAWPCCTdMP6cDWV3dHt1j3ZuH
  access_key: 9QW8RPAZWCXFNLOWSG74
  endpoint: https://ap-south-1.linodeobjects.com
  bucket: scalable

db:
  user: toktik
  database: toktik
  port: 3306
  host: 139.162.35.109:3306
  password: scalable

