redis:
  host: redis
  port: 6379
  db_number: 0
  video_queue: video_queue
  finish_channel: finish_channel
  password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

s3:
  secret_key: TCYSmBQuMOkT2mAPAWPCCTdMP6cDWV3dHt1j3ZuH
  access_key: 9QW8RPAZWCXFNLOWSG74
  endpoint: https://ap-south-1.linodeobjects.com
  bucket: scalable

